import { Download, Features, SectionWrapper } from '@/components'
import Head from 'next/head'
import assets from '../public/assets'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SectionWrapper
        title='Your own NFT marketplace. Start selling and growing.'
        description='Buy, store, collect NFTS, exchange & earn crypto. Join 25+ million people in using proNef marketplace.'
        showBtn
        mockupImg={assets.homeHero}
        banner='banner'
        reverse={false}
      />

      <SectionWrapper
        title='Smart User Interface Marketplace'
        description='Experience a buttery UI of ProNef Nft marketplace. smoth constant colors of fluent UI design'
        showBtn={false}
        mockupImg={assets.homeCards}
        banner=''
        reverse={true}
      />

      <Features />

      <SectionWrapper
        title='Deployment'
        description='ProNef is built using Expo which runs beatifully on all devices. You can easily get your app in peoples hands.'
        showBtn={false}
        mockupImg={assets.feature}
        banner=''
        reverse={true}
      />
      <SectionWrapper
        title='Creative way to showcase the store'
        description='The app contains two screens. The first screen lists all NFTs while the second shows details of a specific NFT.'
        showBtn={false}
        mockupImg={assets.mockup}
        banner='banner02'
        reverse={false}
      />
      <Download />

      <div className={`px-4 py-2 justify-center items-center bg-primary flex-color text-center banner04`}>
        <p className={`my-5 minmd:my-10 font-IBMPlex font-light text-xl minmd:text-3xl minlg:text-4xl minmd:leading-16 text-white`}>
          Made with love by {' '}
          <span className='bold'> Mohammad Hasnat</span>
        </p>
      </div>

    </>
  )
}
