import { Download, Features, SectionWrapper } from '@/components'
import Head from 'next/head'
import assets from '../public/assets'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SectionWrapper
        title='Discover the Future of Digital Asset Trading with ArtiFi'
        description='Buy, store and collect NFTs with our user-friendly platform. Join 10+ million people worldwide.'
        showBtn
        mockupImg={assets.homeHero}
        banner='banner'
        reverse={false}
      />

      <SectionWrapper
        title='Smart User Interface'
        description='Experience an intuitive UI for effortless navigation and seamless transactions'
        showBtn={false}
        mockupImg={assets.homeCards}
        banner=''
        reverse={true}
      />

      <Features />

      <SectionWrapper
        title='Deployment'
        description='Artifi runs beatifully on all devices and can be found in the Expo app store'
        showBtn={false}
        mockupImg={assets.feature}
        banner=''
        reverse={true}
      />
      <SectionWrapper
        title='Creative way to showcase artwork'
        description="Easily navigate a whole catologue of amazing digital art. List your own NFTs or bid for someone else's."
        showBtn={false}
        mockupImg={assets.mockup}
        banner='banner02'
        reverse={false}
      />
      <Download />

      <div className={`px-4 py-5 justify-center items-center bg-primary flex-color text-center banner04`}>
        <p className={`my-5 minmd:my-10 font-IBMPlex font-light text-xl minmd:text-3xl minlg:text-4xl minmd:leading-16 text-white`}>
          Made with love by {' '}
          <span className='bold'> Mohammad Hasnat</span>
        </p>
      </div>

    </>
  )
}
